// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt1F7pvLLs1QjdvObIuZO3DaC6VCwHWr4',
    appId: '1:228672076341:web:0dae8fedc490efd2304f7c',
    messagingSenderId: '228672076341',
    projectId: 'up-heal-0001',
    authDomain: 'up-heal-0001.firebaseapp.com',
    storageBucket: 'up-heal-0001.firebasestorage.app',
  );

  // Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCABrAlPpeRojPIFQlTsVYIc2n8rSEoJZY',
    appId: '1:228672076341:android:868be297f5745073304f7c',
    messagingSenderId: '228672076341',
    projectId: 'up-heal-0001',
    storageBucket: 'up-heal-0001.firebasestorage.app',
  );

  // iOS configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABrAlPpeRojPIFQlTsVYIc2n8rSEoJZY',
    appId: '1:228672076341:ios:a242a6f0c7d593f0304f7c',
    messagingSenderId: '228672076341',
    projectId: 'up-heal-0001',
    storageBucket: 'up-heal-0001.firebasestorage.app',
    iosBundleId: 'com.example.mindquest',
  );

  // macOS configuration (reusing iOS App ID)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCABrAlPpeRojPIFQlTsVYIc2n8rSEoJZY',
    appId: '1:228672076341:ios:a242a6f0c7d593f0304f7c',
    messagingSenderId: '228672076341',
    projectId: 'up-heal-0001',
    storageBucket: 'up-heal-0001.firebasestorage.app',
    iosBundleId: 'com.example.mindquest',
  );

  // Windows configuration (using Web App ID)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCABrAlPpeRojPIFQlTsVYIc2n8rSEoJZY',
    appId: '1:228672076341:web:0dae8fedc490efd2304f7c',
    messagingSenderId: '228672076341',
    projectId: 'up-heal-0001',
    authDomain: 'up-heal-0001.firebaseapp.com',
    storageBucket: 'up-heal-0001.firebasestorage.app',
  );
}
